# Generated by Django 4.2.16 on 2024-12-02 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crazeconcert', '0004_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('seating', models.CharField(choices=[('Front Stage', 'Front Stage'), ('Middle', 'Middle'), ('Balcony', 'Balcony'), ('Others', 'Others')], max_length=20)),
                ('tickets', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
