# Generated by Django 4.2.16 on 2024-12-02 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crazeconcert', '0006_concert_payment_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('date', models.DateField()),
            ],
        ),
    ]
